/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaterialObjectPageObjectPage journey");

        opaTest("Navigate to MaterialObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheMaterialListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMaterialListGenerated.onTable().iCheckRows();
            When.onTheMaterialListGenerated.onTable().iPressRow(0);

            Then.onTheMaterialObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMaterialObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheMaterialObjectPageGenerated.iPressSectionIconTabFilterButton("GeneralData");
            Then.onTheMaterialObjectPageGenerated.iCheckSection({ section: "GeneralData" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "GeneralData" }).iCheckField({ property: "MatId" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "GeneralData" }).iCheckField({ property: "MatDesc" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "GeneralData" }).iCheckField({ property: "MatType" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "GeneralData" }).iCheckField({ property: "BaseUnit" });
            When.onTheMaterialObjectPageGenerated.iPressSectionIconTabFilterButton("PriceStock");
            Then.onTheMaterialObjectPageGenerated.iCheckSection({ section: "PriceStock" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "PriceStock" }).iCheckField({ property: "StockQty" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "PriceStock" }).iCheckField({ property: "UnitPrice" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "PriceStock" }).iCheckField({ property: "CreatedBy" });
            Then.onTheMaterialObjectPageGenerated.onForm({ section: "PriceStock" }).iCheckField({ property: "CreatedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});