/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaterialListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheMaterialListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheMaterialListGenerated.onFilterBar().iCheckFilterField({ property: "MatId" });
            Then.onTheMaterialListGenerated.onFilterBar().iCheckFilterField({ property: "MatDesc" });
            Then.onTheMaterialListGenerated.onFilterBar().iCheckFilterField({ property: "MatType" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheMaterialListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheMaterialListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheMaterialListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheMaterialListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onTheMaterialListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onTheMaterialListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onTheMaterialListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onTheMaterialListGenerated.onTable(defaultTableId).iPressAction("Stok Girişi Yap");
            Then.onTheMaterialListGenerated.onTable(defaultTableId).iCheckAction("Stok Girişi Yap", { enabled: false });
            Then.onTheMaterialListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"MatId":{"header":"Malzeme Kodu"},"MatDesc":{"header":"Malzeme Açıklaması"},"MatType":{"header":"Malzeme Tipi"},"BaseUnit":{"header":"Ölçü Birimi"},"StockQty":{"header":"Mevcut Stok"},"UnitPrice":{"header":"Birim Fiyat"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheMaterialListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMaterialListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheMaterialListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheMaterialObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});